# Generated by Django 6.0.5 on 2026-09-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='accepted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
