# Generated by Django 6.0.7 on 2026-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_bookingrequest_accepted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
