# Generated by Django 6.0.7 on 2026-08-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_state_district_subdistrict'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=200)),
                ('storage_type', models.CharField(choices=[('cold_storage', 'Cold Storage'), ('warehouse', 'Warehouse')], max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity_unit', models.CharField(choices=[('kg', 'Kg'), ('quintal', 'Quintal'), ('ton', 'Ton')], max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('main_contact_number', models.CharField(max_length=15)),
                ('additional_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.state')),
                ('subdistrict', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subdistrict')),
            ],
        ),
    ]
