# Generated by Django 6.0.7 on 2026-08-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_storage_available_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='capacity_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(max_length=50),
        ),
    ]
