# Generated by Django 6.0.5 on 2026-08-22 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_storage_capacity_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='admin_panel.storage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
