# Generated by Django 6.0.5 on 2026-10-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_address_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_username_per_role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
