# Generated by Django 6.0.7 on 2026-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_buyercroprequirement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyercroprequirement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
