# Generated by Django 6.0.7 on 2026-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_alter_buyercroprequirement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyercroprequirement',
            name='price_unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='buyercroprequirement',
            name='quantity_unit',
            field=models.CharField(max_length=20),
        ),
    ]
